# Generated by Django 4.2.23 on 2026-06-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feijian", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="feijianrawrecord",
            new_name="feijian_fei_hospita_86791a_idx",
            old_name="feijian_raw_hospita_idx",
        ),
        migrations.RenameIndex(
            model_name="feijianrawrecord",
            new_name="feijian_fei_import__40695a_idx",
            old_name="feijian_raw_batch_row_idx",
        ),
    ]
