"""
Django settings for medical_audit_project project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=(snnc%&-_3k!umf&e*l(04fsuf(di@dgmn2-k^(g42*cm@$85'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'rules',
    'pricings',
    'tasks',
    'results',
    'cases',
    'repeat_charging',
    'feijian',  # 飞检结果管理
    'rule_import',  # 规则批量导入转换
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders', # 添加 corsheaders
    'rest_framework', 
    'django_filters', # 加上这一行来注册 django-filter！
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # 添加 corsheaders 中间件
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medical_audit_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medical_audit_project.wsgi.application'
LOCAL_DEV_MODE = True

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'medical_insurance',
        'USER': 'root',
        'PASSWORD': '224898504@Wyx',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
    'source_medical_db': {
        'host': os.environ.get('SOURCE_DB_HOST', ''),
        'port': int(os.environ.get('SOURCE_DB_PORT', '3306')),
        'user': os.environ.get('SOURCE_DB_USER', ''),
        'password': os.environ.get('SOURCE_DB_PASSWORD', ''),
        'database': os.environ.get('SOURCE_DB_NAME', ''),
        'charset': 'utf8mb4',
    }
}

SOURCE_MDC_ORG_CD = os.environ.get('SOURCE_MDC_ORG_CD', '')
INHOS_QUERY_MAX_MONTHS = int(os.environ.get('INHOS_QUERY_MAX_MONTHS', '3'))
INHOS_QUERY_MAX_RESULTS = int(os.environ.get('INHOS_QUERY_MAX_RESULTS', '500'))
INHOS_QUERY_TIMEOUT_MS = int(os.environ.get('INHOS_QUERY_TIMEOUT_MS', '120000'))
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# 上传文件存储
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5777",
    "http://localhost:5173", # Vue 开发服务器的地址
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    # 如果你有其他前端地址，也加进来
]
# ... 文件末尾 ...

# Celery Configuration Options
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0' # 使用 Redis 作为消息代理
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0' # 使用 Redis 存储任务结果
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai' # 建议设置为你的时区

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10  # 和你前端的 pageSize 保持一致
}

# ============================================================
# 规则批量导入转换 (rule_import) 配置
# 所有敏感/环境相关项均通过环境变量覆盖，避免硬编码到代码里。
# 部署时通过环境变量设置：
#   RULE_IMPORT_LLM_API_KEY / RULE_IMPORT_LLM_BASE_URL / ...
# ============================================================
import os as _os

# LLM 服务配置
# 默认指向服务器上自部署的 OpenAI 兼容模型（qwen）。
# 注意：base_url 取 OpenAI 兼容的「基址」(以 /v1 结尾)，SDK 会自动拼接
# /chat/completions；不要把完整的 .../chat/completions 路径填进来。
# 自部署模型通常不校验密钥，默认占位 'EMPTY' 即可，仍可由环境变量覆盖。
RULE_IMPORT_LLM_API_KEY = _os.environ.get('RULE_IMPORT_LLM_API_KEY', 'EMPTY')
RULE_IMPORT_LLM_BASE_URL = _os.environ.get(
    'RULE_IMPORT_LLM_BASE_URL', 'http://127.0.0.1:9234/v1',
)
# 判断表头用的模型（自部署仅一个模型，默认与抽取模型一致）
RULE_IMPORT_LLM_MODEL_HEADER = _os.environ.get(
    'RULE_IMPORT_LLM_MODEL_HEADER', 'qwen',
)
# 规则抽取用的模型
RULE_IMPORT_LLM_MODEL_EXTRACT = _os.environ.get(
    'RULE_IMPORT_LLM_MODEL_EXTRACT', 'qwen',
)
# 单次 LLM 请求超时(秒)
RULE_IMPORT_LLM_TIMEOUT = int(_os.environ.get('RULE_IMPORT_LLM_TIMEOUT', '60'))
# 单次 LLM 请求失败重试次数
RULE_IMPORT_LLM_MAX_RETRIES = int(_os.environ.get('RULE_IMPORT_LLM_MAX_RETRIES', '2'))

# 上传文件大小上限(字节)，默认 50MB
RULE_IMPORT_MAX_FILE_SIZE = int(
    _os.environ.get('RULE_IMPORT_MAX_FILE_SIZE', str(50 * 1024 * 1024)),
)
# 允许的文件类型
RULE_IMPORT_ALLOWED_EXTS = ('pdf', 'xlsx', 'xls')

# LLM 分块行数：每次送入大模型抽取的表格行数。仅后端配置，前端不暴露。
RULE_IMPORT_DEFAULT_CHUNK_SIZE = int(
    _os.environ.get('RULE_IMPORT_DEFAULT_CHUNK_SIZE', '10'),
)

# Celery 任务执行时间限制(秒)：抽取任务可能很长
RULE_IMPORT_TASK_SOFT_TIME_LIMIT = int(
    _os.environ.get('RULE_IMPORT_TASK_SOFT_TIME_LIMIT', str(60 * 60)),  # 1h
)
RULE_IMPORT_TASK_TIME_LIMIT = int(
    _os.environ.get('RULE_IMPORT_TASK_TIME_LIMIT', str(60 * 60 + 300)),  # 1h5m
)
