# Generated by Django 4.2.23 on 2025-08-22 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '处理中'), ('completed', '已完成'), ('failed', '失败')], db_index=True, default='pending', max_length=20, verbose_name='任务状态')),
                ('hospitalization_ids', models.JSONField(verbose_name='待审核住院号列表')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='任务摘要/报告')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '审核任务',
                'verbose_name_plural': '审核任务',
            },
        ),
        migrations.CreateModel(
            name='TaskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.rule')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'unique_together': {('task', 'rule')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='rules',
            field=models.ManyToManyField(through='tasks.TaskRule', to='rules.rule', verbose_name='关联规则'),
        ),
    ]
