# Generated by Django 4.2.23 on 2025-09-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='selected_schemas',
            field=models.JSONField(blank=True, default=list, verbose_name='选择的检测方案'),
        ),
    ]
