# Generated by Django 4.2.7 on 2025-11-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_repeat_charging_child_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repeat_charging_pairs',
            field=models.JSONField(blank=True, default=list, verbose_name='重复收费选择的父-子医保编码对'),
        ),
    ]
