# Generated by Codex on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_repeat_charging_pairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mdc_org_cd',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='医疗机构代码'),
        ),
    ]
