# Generated by Django 4.2.23 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_mdc_org_cd'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='self_reflection',
            field=models.TextField(blank=True, default='', verbose_name='计算自检结果'),
        ),
    ]
