# Generated by Django 4.2.23 on 2025-08-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('hospitalization_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='住院流水号')),
                ('json_content', models.JSONField(verbose_name='病历JSON内容')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '缓存病历',
                'verbose_name_plural': '缓存病历',
            },
        ),
    ]
