# Generated by Django 4.2.7 on 2025-11-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repeat_charging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentchildrelation',
            name='child_insurance_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='子项目医保统一编码'),
        ),
        migrations.AlterField(
            model_name='parentchildrelation',
            name='parent_insurance_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='父项目医保统一编码'),
        ),
    ]
