# Generated by Django 4.2.7 on 2025-11-06 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repeat_charging', '0003_parentchildrelation_child_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentchildrelation',
            options={'ordering': ['parent_charge_code', 'child_order', 'id'], 'verbose_name': '父子项目映射', 'verbose_name_plural': '父子项目映射'},
        ),
    ]
