# Generated by Django 4.2.23 on 2026-06-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleImportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, default='', max_length=255, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('parsing', '解析中'), ('extracting', '抽取中'), ('success', '转换成功'), ('failed', '转换失败'), ('canceled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='任务状态')),
                ('stage', models.CharField(blank=True, default='', max_length=20, verbose_name='当前阶段')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(0-100)')),
                ('original_file', models.FileField(blank=True, null=True, upload_to='rule_imports/%Y/%m/', verbose_name='原始文件')),
                ('file_name', models.CharField(blank=True, default='', max_length=512, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(blank=True, default='', max_length=10, verbose_name='文件类型')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='输入参数')),
                ('table_count', models.IntegerField(default=0, verbose_name='解析出的表数')),
                ('rule_count', models.IntegerField(default=0, verbose_name='抽取规则数')),
                ('imported_count', models.IntegerField(default=0, verbose_name='已入库规则数')),
                ('error_detail', models.TextField(blank=True, default='', verbose_name='异常信息')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Celery任务ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始执行时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '规则导入任务',
                'verbose_name_plural': '规则导入任务',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='rule_import_status_346b8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExtractedRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=0, help_text='算法内 rule_id 序号', verbose_name='序号')),
                ('rule_type', models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='规则类型')),
                ('constrained_object', models.CharField(blank=True, default='', max_length=255, verbose_name='约束对象')),
                ('constraint_value', models.TextField(blank=True, default='', verbose_name='限制内容')),
                ('evidence', models.JSONField(blank=True, default=dict, verbose_name='原始命中行')),
                ('source', models.JSONField(blank=True, default=dict, verbose_name='来源信息')),
                ('is_selected', models.BooleanField(default=True, verbose_name='是否勾选')),
                ('is_imported', models.BooleanField(default=False, verbose_name='是否已入库')),
                ('imported_rule_id', models.CharField(blank=True, default='', help_text='写入 rules.Rule 后的 rule_id', max_length=50, verbose_name='关联正式规则ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('import_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rule_import.ruleimporttask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '抽取规则',
                'verbose_name_plural': '抽取规则',
                'ordering': ['import_task', 'seq'],
                'indexes': [models.Index(fields=['rule_type'], name='rule_import_rule_ty_c36b91_idx'), models.Index(fields=['import_task', 'seq'], name='rule_import_import__8c0c2d_idx')],
            },
        ),
    ]
