# Generated by Django 4.2.23 on 2025-08-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTemplate',
            fields=[
                ('template_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='模板ID')),
                ('description', models.CharField(max_length=255, verbose_name='模板描述')),
                ('template_json', models.JSONField(verbose_name='模板JSON结构')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '审核模板',
                'verbose_name_plural': '审核模板',
            },
        ),
        migrations.CreateModel(
            name='MedicalCode',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='药品代码')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='国家医保药品名称')),
            ],
            options={
                'verbose_name': '医保药品代码',
                'verbose_name_plural': '医保药品代码',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(help_text='业务规则ID，如 rule_001', max_length=50, unique=True, verbose_name='规则号')),
                ('drug_name', models.CharField(db_index=True, max_length=255, verbose_name='药品名称')),
                ('description', models.TextField(verbose_name='规则描述')),
                ('logic_expression', models.TextField(verbose_name='逻辑表达式')),
                ('status', models.BooleanField(default=True, verbose_name='是否启用')),
                ('type', models.CharField(blank=True, db_index=True, default='超限定用药', max_length=50, verbose_name='规则类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '审核规则',
                'verbose_name_plural': '审核规则',
            },
        ),
    ]
