# Generated by Django 4.2.23 on 2025-12-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_add_rule_code_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_name', models.CharField(db_index=True, help_text='例如 is_acute_stroke', max_length=100, unique=True, verbose_name='函数名称')),
                ('description', models.TextField(blank=True, help_text='LLM生成的函数说明', verbose_name='函数描述')),
                ('function_body', models.TextField(help_text='完整的 Python 函数定义代码', verbose_name='函数代码')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '业务函数',
                'verbose_name_plural': '业务函数',
            },
        ),
    ]
