# Generated by Django 4.2.7 on 2026-01-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_businessfunction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='drug_name',
        ),
        migrations.AddField(
            model_name='rule',
            name='rule_name',
            field=models.CharField(blank=True, db_index=True, help_text='规则名称，如药品名称或收费项目名称', max_length=255, verbose_name='规则名称'),
        ),
    ]
