# Generated by Django 4.2.7 on 2026-01-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_remove_rule_drug_name_rule_rule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='rule_name',
        ),
        migrations.AddField(
            model_name='rule',
            name='drug_name',
            field=models.CharField(blank=True, db_index=True, help_text='药品名称或收费项目名称，用于匹配', max_length=255, verbose_name='药品名称'),
        ),
    ]
