# Generated by Django 4.2.23 on 2025-09-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardChargeItem',
            fields=[
                ('charge_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='收费编码')),
                ('item_name', models.CharField(db_index=True, max_length=255, verbose_name='收费名称')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='单位')),
                ('price_2021', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='2021价格')),
                ('price_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='2024价格(单价)')),
                ('insurance_code', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='医保编码')),
                ('description_2021', models.TextField(blank=True, null=True, verbose_name='2021说明')),
                ('description_2024', models.TextField(blank=True, null=True, verbose_name='2024说明')),
            ],
            options={
                'verbose_name': '标准收费项目',
                'verbose_name_plural': '标准收费项目',
            },
        ),
    ]
